export const imageLinks: Record<string, string> = {
  'cloak & dagger': 'https://marvelrivals.wiki.gg/images/Cloak_%26_Dagger_Lord_Icon.png',
  'daredevil': 'https://marvelrivals.wiki.gg/images/Daredevil_Lord_Icon.png',
  'gambit': 'https://marvelrivals.wiki.gg/images/Gambit_Lord_Icon.png',
  'angela': 'https://marvelrivals.wiki.gg/images/Angela_Lord_Icon.png',
  'jeff the land shark': 'https://marvelrivals.wiki.gg/images/Jeff_The_Landshark_Lord_Icon.png',
  'invisible woman': 'https://marvelrivals.wiki.gg/images/Invisible_Woman_Lord_Icon.png',
  'emma frost': 'https://marvelrivals.wiki.gg/images/Emma_Frost_Lord_Icon.png',
  'luna snow': 'https://marvelrivals.wiki.gg/images/Luna_Snow_Lord_Icon.png',
  'doctor strange': 'https://marvelrivals.wiki.gg/images/Doctor_Strange_Lord_Icon.png',
  'rocket raccoon': 'https://marvelrivals.wiki.gg/images/Rocket_Raccoon_Lord_Icon.png',
  'peni parker': 'https://marvelrivals.wiki.gg/images/Peni_Parker_Lord_Icon.png',
  'thor': 'https://marvelrivals.wiki.gg/images/Thor_Lord_Icon.png',
  'moon knight': 'https://marvelrivals.wiki.gg/images/Moon_Knight_Lord_Icon.png',
  'scarlet witch': 'https://marvelrivals.wiki.gg/images/Scarlet_Witch_Lord_Icon.png',
  'magneto': 'https://marvelrivals.wiki.gg/images/Magneto_Lord_Icon.png',
  'the punisher': 'https://marvelrivals.wiki.gg/images/The_Punisher_Lord_Icon.png',
  'squirrel girl': 'https://marvelrivals.wiki.gg/images/Squirrel_Girl_Lord_Icon.png',
  'iron man': 'https://marvelrivals.wiki.gg/images/Iron_Man_Lord_Icon.png',
  'the thing': 'https://marvelrivals.wiki.gg/images/The_Thing_Lord_Icon.png',
  'winter soldier': 'https://marvelrivals.wiki.gg/images/Winter_Soldier_Lord_Icon.png',
  'groot': 'https://marvelrivals.wiki.gg/images/Groot_Lord_Icon.png',
  'venom': 'https://marvelrivals.wiki.gg/images/Venom_Lord_Icon.png',
  'phoenix': 'https://marvelrivals.wiki.gg/images/Phoenix_Lord_Icon.png',
  'ultron': 'https://marvelrivals.wiki.gg/images/Ultron_Lord_Icon.png',
  'mantis': 'https://marvelrivals.wiki.gg/images/Mantis_Lord_Icon.png',
  'hela': 'https://marvelrivals.wiki.gg/images/Hela_Lord_Icon.png',
  'namor': 'https://marvelrivals.wiki.gg/images/Namor_Lord_Icon.png',
  'magik': 'https://marvelrivals.wiki.gg/images/Magik_Lord_Icon.png',
  'hulk': 'https://marvelrivals.wiki.gg/images/Hulk_Lord_Icon.png',
  'spider-man': 'https://marvelrivals.wiki.gg/images/Spider-Man_Lord_Icon.png',
  'star-lord': 'https://marvelrivals.wiki.gg/images/Star-Lord_Lord_Icon.png',
  'captain america': 'https://marvelrivals.wiki.gg/images/Captain_America_Lord_Icon.png',
  'psylocke': 'https://marvelrivals.wiki.gg/images/Psylocke_Lord_Icon.png',
  'loki': 'https://marvelrivals.wiki.gg/images/Loki_Lord_Icon.png',
  'blade': 'https://marvelrivals.wiki.gg/images/Blade_Lord_Icon.png',
  'adam warlock': 'https://marvelrivals.wiki.gg/images/Adam_Warlock_Lord_Icon.png',
  'mister fantastic': 'https://marvelrivals.wiki.gg/images/Mister_Fantastic_Lord_Icon.png',
  'black panther': 'https://marvelrivals.wiki.gg/images/Black_Panther_Lord_Icon.png',
  'hawkeye': 'https://marvelrivals.wiki.gg/images/Hawkeye_Lord_Icon.png',
  'iron fist': 'https://marvelrivals.wiki.gg/images/Iron_Fist_Lord_Icon.png',
  'human torch': 'https://marvelrivals.wiki.gg/images/Human_Torch_Lord_Icon.png',
  'wolverine': 'https://marvelrivals.wiki.gg/images/Wolverine_Lord_Icon.png',
  'storm': 'https://marvelrivals.wiki.gg/images/Storm_Lord_Icon.png',
  'black widow': 'https://marvelrivals.wiki.gg/images/Black_Widow_Lord_Icon.png'
};
