"use client";

export default function Home() {

  const text = "GameSense".split("");
  const colors = [
    "text-purple-500",
    "text-white",
  ];

  return (
    <div className="font-sans min-h-screen w-full bg-gradient-to-br from-gray-900 via-gray-800 to-black text-white p-8 sm:p-20">

  {/* Hero Section */}
  <main className="flex flex-col gap-10 items-center max-w-4xl mx-auto text-center mt-10">

    <h1 className="text-4xl sm:text-5xl font-extrabold tracking-wide font-serif">
      Welcome to&nbsp;
      {text.map((char, i) => (
            <span
              key={i}
              className={`${colors[i % colors.length]} transition drop-shadow-[0_0_4px_rgba(168,85,247,0.5)]`}
            >
              {char}
            </span>
          ))}
    </h1>

    <p className="text-lg text-gray-300 max-w-2xl">
      Your personal AI-powered companion for mastering <span className="text-purple-300 font-semibold">Marvel Rivals</span>.
      Track your stats, climb the ranks, and get tailored coaching insights driven by LLMs.
    </p>

    {/* Call to Action */}
    <a
      href="/home"
      className="mt-4 px-8 py-3 bg-purple-600 hover:bg-purple-700 text-white rounded-xl text-lg font-semibold shadow-lg hover:shadow-purple-500/40 transition-all"
    >
      Get Started
    </a>

    {/* Features */}
    <section className="grid grid-cols-1 sm:grid-cols-2 gap-8 mt-12 w-full">

      <div className="p-6 rounded-xl bg-gray-800/70 backdrop-blur border border-gray-700 shadow-md hover:shadow-purple-500/20 transition-all">
        <h2 className="text-xl font-bold text-purple-300 mb-2">🎯 Player Stat Tracking</h2>
        <p className="text-gray-300 text-sm">
          Enter your gamer tag to instantly retrieve your match history, accuracy, kills, deaths, assists, MVPs, and more.
        </p>
      </div>

      <div className="p-6 rounded-xl bg-gray-800/70 backdrop-blur border border-gray-700 shadow-md hover:shadow-purple-500/20 transition-all">
        <h2 className="text-xl font-bold text-purple-300 mb-2">📈 Global Leaderboard</h2>
        <p className="text-gray-300 text-sm">
          Compare yourself against the top players and filter rankings by kills, win rate, MVPs, and more.
        </p>
      </div>

      <div className="p-6 rounded-xl bg-gray-800/70 backdrop-blur border border-gray-700 shadow-md hover:shadow-purple-500/20 transition-all">
        <h2 className="text-xl font-bold text-purple-300 mb-2">🤖 AI Performance Coaching</h2>
        <p className="text-gray-300 text-sm">
          Get personalized gameplay tips generated by cutting-edge AI to help you improve faster.
        </p>
      </div>

      <div className="p-6 rounded-xl bg-gray-800/70 backdrop-blur border border-gray-700 shadow-md hover:shadow-purple-500/20 transition-all">
        <h2 className="text-xl font-bold text-purple-300 mb-2">📊 Deep Match Insights</h2>
        <p className="text-gray-300 text-sm">
          Analyze your strengths and weaknesses across different heroes, maps, and match types.
        </p>
      </div>

    </section>

    {/* Quick Start Guide */}
    <section className="mt-14 w-full max-w-xl">
      <h3 className="text-2xl font-bold text-purple-300 mb-4 text-center">How to Get Started</h3>

      <ol className="list-decimal list-inside text-gray-300 text-left space-y-2 text-md">
        <li>Click <span className="font-semibold text-white">Get Started</span> or open <span className="font-semibold text-white">Homepage</span>.</li>
        <li>Enter your gamer tag to fetch your stats.</li>
        <li>View your rank, match history, and performance summaries.</li>
        <li>Generate AI-powered recommendations to improve your gameplay.</li>
        <li>Visit the Leaderboard to see how you compare globally.</li>
      </ol>
    </section>

  </main>

  <footer className="mt-20 flex justify-center text-gray-500 text-sm">
    © {new Date().getFullYear()} Rivals Coach — Not affiliated with NetEase or Marvel.
  </footer>

</div>

  );
}
